spring:
  application:
    name: journalApp
  datasource:

    url: jdbc:mysql://localhost:3306/journal_db
    password: Dattatray@4141
    username: root

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8081