#Weather api key
weather:
  api:
    key: api_key
#for database configuration setup
spring:
  application:
    name: journalApp
  datasource:
    url: jdbc:mysql://localhost:3306/journal_db
    password: dp_pass
    username: root
  #redis configuration
  data:
    redis:
      host: localhost
      port: 6379

  #mail sender configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: youremail@gmail.com
    password: xxxxxxxxxxxx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jpa:
    hibernate:
      ddl-auto: update
#to set server port and path
server:
  port: 8080
  #also can set path
#  servlet:
#    context-path: 